#!/usr/bin/env python3
"""Generate source/generated/Strings.mc from the six strings.xml resource files.

Connect IQ picks a compiled string resource by the system locale and cannot
switch it at runtime. To support an in-app language switcher we emit a plain
Monkey C table keyed by language code so the app can look translations up (and
change them) at runtime. Only the base "eng" strings.xml is guaranteed to be a
superset; all six are kept in sync by CI, so we read keys per language.

Run: python3 scripts/generate_strings.py
"""

import os
import xml.etree.ElementTree as ET

# Language code -> resource folder. "eng" is the base (default) resource dir.
LANGUAGES = [
    ("eng", "resources"),
    ("por", "resources-por"),
    ("spa", "resources-spa"),
    ("fre", "resources-fre"),
    ("deu", "resources-deu"),
    ("ita", "resources-ita"),
]

# Native language names shown in the in-app language menu.
NATIVE_NAMES = {
    "eng": "English",
    "por": "Português",
    "spa": "Español",
    "fre": "Français",
    "deu": "Deutsch",
    "ita": "Italiano",
}

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(REPO_ROOT, "source", "generated", "Strings.mc")


def read_strings(folder):
    """Return an ordered {id: value} dict from a folder's strings.xml.

    ElementTree unescapes XML entities (&amp; -> &, etc.) for us.
    """
    path = os.path.join(REPO_ROOT, folder, "strings", "strings.xml")
    tree = ET.parse(path)
    root = tree.getroot()
    result = {}
    for node in root.findall("string"):
        key = node.get("id")
        value = node.text if node.text is not None else ""
        result[key] = value
    return result


def mc_string_literal(value):
    """Escape a Python string into a Monkey C double-quoted string literal."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def emit_dictionary(entries, indent):
    """Emit a Monkey C dictionary literal body from an ordered {key: value}."""
    pad = " " * indent
    lines = []
    for key, value in entries.items():
        lines.append(
            "%s%s => %s"
            % (pad, mc_string_literal(key), mc_string_literal(value))
        )
    return ",\n".join(lines)


def main():
    tables = {}
    for code, folder in LANGUAGES:
        tables[code] = read_strings(folder)

    # Presentation/key order follows the base (eng) file.
    base_order = list(tables["eng"].keys())

    codes = [code for code, _ in LANGUAGES]

    out = []
    out.append("// AUTO-GENERATED by scripts/generate_strings.py. DO NOT EDIT.")
    out.append("//")
    out.append("// Runtime i18n table. Connect IQ selects compiled string")
    out.append("// resources by system locale and cannot switch them at runtime,")
    out.append("// so translations live here and are chosen by language code.")
    out.append("import Toybox.Lang;")
    out.append("")
    out.append("module I18n {")

    codes_literal = ", ".join('"%s"' % c for c in codes)
    out.append("    const CODES = [%s];" % codes_literal)

    names_pairs = ", ".join(
        '"%s"=>%s' % (c, mc_string_literal(NATIVE_NAMES[c])) for c in codes
    )
    out.append("    const NAMES = { %s };" % names_pairs)
    out.append("")
    out.append("    // Returns the {key=>value} dictionary for ONE code so only the")
    out.append("    // chosen language is allocated. The default branch returns eng.")
    out.append("    function table(code as Lang.String) as Lang.Dictionary {")

    # Every non-eng code gets its own branch; eng is the default fallthrough.
    for code in codes:
        if code == "eng":
            continue
        # Fall back to the eng value for any key missing in a translation.
        entries = {}
        for key in base_order:
            entries[key] = tables[code].get(key, tables["eng"][key])
        out.append('        if (code.equals("%s")) {' % code)
        out.append("            return {")
        out.append(emit_dictionary(entries, 16))
        out.append("            };")
        out.append("        }")

    eng_entries = {key: tables["eng"][key] for key in base_order}
    out.append("        return {")
    out.append(emit_dictionary(eng_entries, 12))
    out.append("        };")
    out.append("    }")
    out.append("}")
    out.append("")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))

    print(
        "Generated %s: %d languages, %d keys each"
        % (
            os.path.relpath(OUTPUT_PATH, REPO_ROOT),
            len(codes),
            len(base_order),
        )
    )


if __name__ == "__main__":
    main()
